[#ftl]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kontrola věku</title>
    <link rel="stylesheet" href="/css/style.css"/>
</head>
<body>
<div class = "container">
    <div class = "basket">
        <h2>Chyba registrace</h2>
        <div class ="text">Na letní tábor lze zaregistrovat pouze děti ve věku 9  až 15 let.</div><br>
        <a href="/">Zpět na formulář registrace.</a>
    </div>
</div>
</body>
</html>
